---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpus: 2

provisioner:
  name: chef_solo
  require_chef_omnibus: latest
  chef_omnibus_install_options: -d /tmp/vagrant-cache/vagrant_omnibus

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[lxctests::install_chef_provisioning]
      - recipe[lxctests::simple3]
    attributes: {
      apt: {
        compile_time_update: true
      },
      build-essential: {
        compile_time: true
      },
      lxctests: {
        numfiles: 10,
        use_chef_provisioning_head: false,
        use_chef_provisioning_lxc_head: true
      }
    }
